---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: "Force=true"
spec:
  manualSelector: false
  template:
    metadata:
      labels:
        app: migration-job
        job-name: migration-job
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["echo", "Done✅✅-3"]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    lb: name
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: main
          image: nginx:latest
          ports:
          - name: liveness-port
            containerPort: 80
          startupProbe:
            initialDelaySeconds: 1
            httpGet:
              path: /
              port: liveness-port
